style: test scripts and Dockerfiles

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 PROJECT_ROOT=$(dirname "$DIR")
 
 ROLE_NAME="$(basename "$PROJECT_ROOT")"
@@ -9,19 +9,20 @@ TEST_HOME=/home/test
 ###
 # Detect Windows Subsystem for Linux
 ###
-function detect_wsl {
-    if grep -q Microsoft /proc/version; then
-        echo "*** Windows Subsystem for Linux detected"
-        is_wsl=1
-    else
-        is_wsl=0
+detect_wsl() {
+    is_wsl=0
+    if [ -e "/proc/version" ]; then
+        if grep -q Microsoft /proc/version; then
+            echo "*** Windows Subsystem for Linux detected"
+            is_wsl=1
+        fi
     fi
 }
 
 ###
 # Stop all containers
 ###
-function finish {
+finish() {
     local containers=""
     containers=$(docker ps -q --filter=name="${ROLE_NAME}")
     if [ -n "${containers}" ]; then
@@ -33,7 +34,7 @@ function finish {
 ###
 # Stop container
 ###
-function stop {
+stop() {
     local image=$1
     local container_name="${ROLE_NAME}-${image}-tests"
     echo "*** Stop containers"
@@ -43,7 +44,7 @@ function stop {
 ###
 # Build image
 ###
-function build {
+build() {
     local image=$1
     local image_name="${ROLE_NAME}-${image}"
     echo "*** Build image"
@@ -53,7 +54,7 @@ function build {
 ###
 # Start container in the background
 ###
-function start {
+start() {
     local image=$1
     local image_name="${ROLE_NAME}-${image}"
     local container_name="${ROLE_NAME}-${image}-tests"
@@ -67,7 +68,7 @@ function start {
 ###
 # Run tests in the container
 ###
-function run_tests {
+run_tests() {
     local image=$1
     local container_name="${ROLE_NAME}-${image}-tests"
     echo "*** Run tests"
@@ -77,16 +78,18 @@ function run_tests {
         "${TEST_HOME}/${ROLE_NAME}/tests/run-tests-docker"
 }
 
+command -v docker >/dev/null || { echo "docker not found"; exit 1; }
+
 trap finish EXIT
 
 detect_wsl
 
 cd "${DIR}"
 
-images=( "$@" )
+images=("$@")
 if [ ${#images[@]} -eq 0 ]; then
-    images=( */Dockerfile )
-    images=( "${images[@]/\/Dockerfile/}" )
+    images=(*/Dockerfile)
+    images=("${images[@]/\/Dockerfile/}")
 fi
 
 cd "${PROJECT_ROOT}"
diff --git a/tests/run-tests-docker b/tests/run-tests-docker
--- a/tests/run-tests-docker
+++ b/tests/run-tests-docker
@@ -1,18 +1,14 @@
 #!/usr/bin/env bash
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 PROJECT_ROOT=$(dirname "$DIR")
-
-ROLE_NAME="$(basename "$PROJECT_ROOT")"
 
 set -e
 
-ansible --version
-
 # Paths in which Ansible will search for Roles
-export ANSIBLE_ROLES_PATH="$ROLE_NAME"
+export ANSIBLE_ROLES_PATH=$(dirname "$PROJECT_ROOT")
 
-cd "$PROJECT_ROOT"
+cd "${PROJECT_ROOT}"
 
 echo "*** Check syntax"
 
@@ -25,11 +21,10 @@ ansible-playbook tests/test.yml -i tests/inventory --connection=local -v
 echo "*** Idempotence test"
 
 # shellcheck disable=SC2015
-ansible-playbook tests/test.yml -i tests/inventory --connection=local \
-    | grep -q 'changed=0.*failed=0' \
-    && (echo 'Idempotence test: pass' && exit 0) \
-    || (echo 'Idempotence test: fail' && exit 1)
-
+ansible-playbook tests/test.yml -i tests/inventory --connection=local |
+    grep -q 'changed=0.*failed=0' &&
+    (echo 'Idempotence test: pass' && exit 0) ||
+    (echo 'Idempotence test: fail' && exit 1)
 
 echo "*** Verify installed Node.js version"
 
