style: tests/run-tests and tests/run-tests-docker

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -6,9 +6,12 @@ PROJECT_ROOT=$(dirname "$DIR")
 ROLE_NAME="$(basename "$PROJECT_ROOT")"
 TEST_HOME=/home/test
 
-###
+# Print error into STDERR
+error() {
+    echo "$@" 1>&2
+}
+
 # Detect Windows Subsystem for Linux
-###
 detect_wsl() {
     is_wsl=0
     if [ -e "/proc/version" ]; then
@@ -19,9 +22,7 @@ detect_wsl() {
     fi
 }
 
-###
 # Stop all containers
-###
 finish() {
     local containers=""
     containers=$(docker ps -q --filter=name="${ROLE_NAME}")
@@ -31,9 +32,7 @@ finish() {
     fi
 }
 
-###
 # Stop container
-###
 stop() {
     local image=$1
     local container_name="${ROLE_NAME}-${image}-tests"
@@ -41,9 +40,7 @@ stop() {
     docker stop "${container_name}"
 }
 
-###
 # Build image
-###
 build() {
     local image=$1
     local image_name="${ROLE_NAME}-${image}"
@@ -51,9 +48,7 @@ build() {
     docker build -t "${image_name}" "./tests/${image}"
 }
 
-###
 # Start container in the background
-###
 start() {
     local image=$1
     local image_name="${ROLE_NAME}-${image}"
@@ -65,9 +60,7 @@ start() {
         "${image_name}"
 }
 
-###
 # Run tests in the container
-###
 run_tests() {
     local image=$1
     local container_name="${ROLE_NAME}-${image}-tests"
@@ -78,8 +71,9 @@ run_tests() {
         "${TEST_HOME}/${ROLE_NAME}/tests/run-tests-docker"
 }
 
+# Check if Docker is installed
 command -v docker >/dev/null || {
-    echo "docker not found"
+    error "docker not found"
     exit 1
 }
 
@@ -89,7 +83,10 @@ detect_wsl
 
 cd "${DIR}"
 
+# Use image name from command line parameters
 images=("$@")
+
+# Find all Docker images if desired image is not specified
 if [ ${#images[@]} -eq 0 ]; then
     images=(*/Dockerfile)
     images=("${images[@]/\/Dockerfile/}")
@@ -97,6 +94,7 @@ fi
 
 cd "${PROJECT_ROOT}"
 
+# Update mount root path if running on WSL
 if [ "${is_wsl}" == "1" ]; then
     MOUNT_ROOT="$(pwd -P | sed 's~/mnt/c/~c:/~')"
 else
@@ -105,10 +103,12 @@ fi
 
 set -e
 
+# Build all Docker images
 for i in "${images[@]}"; do
     build "$i"
 done
 
+# Run all tests
 for i in "${images[@]}"; do
     start "$i"
     run_tests "$i"
